import { UserRole } from "@/types/auth";

export const ROLE_LABELS: Record<UserRole, string> = {
  SUPER_ADMIN: "Super Admin",
  PROJECT_MANAGER: "Project Manager",
  ARCHITECT: "Architect",
  ENGINEER: "Civil Engineer",
  CLIENT: "Client",
};

export const DASHBOARD_PATH_BY_ROLE: Record<UserRole, string> = {
  SUPER_ADMIN: "/dashboard/super-admin",
  PROJECT_MANAGER: "/dashboard/project-manager",
  ARCHITECT: "/dashboard/architect",
  ENGINEER: "/dashboard/engineer",
  CLIENT: "/dashboard/client",
};

export const MODULE_PERMISSIONS: Record<UserRole, string[]> = {
  SUPER_ADMIN: [
    "dashboard",
    "clients",
    "projects",
    "materials",
    "cost-estimation",
    "decision-logs",
    "ai-interview",
    "risk-intelligence",
    "planning-assistant",
    "sustainability",
    "blueprint-analyzer",
    "site-monitoring",
    "suppliers",
    "workforce",
    "construction-knowledge",
    "settings",
  ],
  PROJECT_MANAGER: [
    "dashboard",
    "clients",
    "projects",
    "materials",
    "cost-estimation",
    "decision-logs",
    "ai-interview",
    "risk-intelligence",
    "planning-assistant",
    "sustainability",
    "site-monitoring",
    "suppliers",
    "workforce",
    "construction-knowledge",
  ],
  ARCHITECT: [
    "dashboard",
    "projects",
    "materials",
    "ai-interview",
    "decision-logs",
    "risk-intelligence",
    "planning-assistant",
    "sustainability",
    "blueprint-analyzer",
    "suppliers",
    "construction-knowledge",
  ],
  ENGINEER: [
    "dashboard",
    "projects",
    "materials",
    "cost-estimation",
    "decision-logs",
    "risk-intelligence",
    "planning-assistant",
    "site-monitoring",
    "suppliers",
    "workforce",
    "construction-knowledge",
  ],
  CLIENT: [
    "dashboard",
    "clients",
    "projects",
    "cost-estimation",
    "risk-intelligence",
    "sustainability",
    "site-monitoring",
    "construction-knowledge",
  ],
};
